### ISSUE TITLE
When the "Format XAML on save" option is enabled, saving all (Ctrl+Shift+S) should only process unsaved modified XAML files

### ISSUE THREAD

**Issue by peterM** [Xavalon/XamlStyler#142]
There is defect when i save all documents or use  (Ctrl+Shift + S).
I expect to format only unsaved || opened documents and not all documents with *.xaml extension in solution.

**Comment by phraemer** [comment]
Yeah. This means I have to uninstall it. Too much noise otherwise.

**Comment by grochocki** [comment]
This is definitely a pain point, though it can be easily mitigated in the short term by disabling the "Format XAML on save" option. There are a number of feature requests that should improve this experience overall:
- #56: Support right-click to format on files and folders in solution explorer
- #67: Format Selection
- #95: Make 'Format XAML on save' setting default to False
- #132: Hide the "Format XAML" option outside of the XAML editor

I would consider this a bug on the "Format XAML on save" option (i.e., not intended behavior). Formatting all files is covered by #56.

**Comment by peterM** [comment]
You could Merge at least new Filter from #144 
x.Where(d=> d.Window !=null)
What will filter out documents what are not opened. And i think this additional Where() solve issue of this issue.

**Comment by grochocki** [comment]
Fixed via #220 -- should only format opened documents now.

**Comment by avdynut** [comment]
This issue occurs after I updated XamlStyler to version 3.2003.9.
Steps to reproduce:

1. Open any .xaml file
2. Click Save All button

Actual behavior: all xaml files in the solution are formatted

**Comment by LoriBru** [comment]
Why is this closed? Apparently, it's still an issue in 2022.

**Comment by peterM** [comment]
Upper is my code what solved the problem in my case. :) .. if i remember correctly i cloned repo and built extension with my fix and stopped use official extension :)

**Comment by LoriBru** [comment]
Thank you for the info :) I just wonder why this is not fixed as well in the official extension version!

**Comment by NicoVermeir** [comment]
looks like we lost track of this one. thanks for the reminder folks, we'll look into it!
@peterM thanks for the suggestion, we'll look into your code snippet to see if it fixes this issue without raising additional ones :)

**Comment by jstevenson72** [comment]
Yes, I have to stop using this on my team.  Because we have 20 xaml files, and and everytime someone asks to save all unsaved documents, this extension rewriting every Xaml file.  Why is this issue closed?  This should be re-opened since this has been occurring again since 2022.

**Comment by peterM** [comment]
> looks like we lost track of this one. thanks for the reminder folks, we'll look into it! @peterM thanks for the suggestion, we'll look into your code snippet to see if it fixes this issue without raising additional ones :)

Sure .. looks like 6 years of searching where the problem is were much better spent effort than try my proposed solution 🤷‍♂️
